# Generated by Django 6.0.7 on 2026-08-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='cookie_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
