# Generated by Django 6.0.7 on 2026-08-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_contractor_cookie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='payout_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='name',
            field=models.CharField(default='there', max_length=100),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
