# Generated by Django 6.0.7 on 2026-08-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_contractor_email_contractor_payout_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractor',
            old_name='payout_details',
            new_name='bank_details',
        ),
        migrations.AddField(
            model_name='contractor',
            name='square_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='stripe_link',
            field=models.URLField(blank=True),
        ),
    ]
