# Generated by Django 6.0.7 on 2026-08-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_rename_payout_details_contractor_bank_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='default_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
